In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv('data/events_up_to_01062018.csv', low_memory=False)
df.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,Samsung Galaxy J7 Prime,Excelente,32GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iPhone 5s,Muito Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iPhone 6S,Muito Bom,64GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iPhone 7,Bom,128GB,Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,LG G4 H818P,Excelente,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df = df.loc[df["event"] == "conversion"]
df["model_2"] = df["model"].apply(lambda x: x.split(" ")[0])
df_m = df.groupby("person")["model_2"].value_counts().to_frame()
df_m.columns = ['cant']
df_m = df_m.reset_index()
celulares = df_m["model_2"].value_counts()
celulares

Samsung     2191
iPhone      1331
Motorola     742
LG           106
Lenovo        73
Sony          39
Asus          16
iPad           6
Quantum        3
Name: model_2, dtype: int64

In [20]:
df_m = df_m.drop_duplicates(subset="person", keep='first')
df_m

        person   model_2  cant
0     000ba417  Motorola     1
1     001001be    iPhone     1
2     001804a2    iPhone     1
3     0019e639  Motorola     1
5     001b0bf9   Samsung     1
6     0020152e   Samsung     1
7     002aea56    iPhone     4
8     002ed810   Samsung     2
9     0038a117      Asus     1
10    0043a48e   Samsung     3
11    004ed8ba   Samsung     1
12    00546f4c   Samsung     4
13    00750af8   Samsung     1
14    0076b7dc    iPhone     1
15    00971729  Motorola     1
16    009944e1  Motorola     1
17    009f8292    iPhone     2
18    00caa482    iPhone     4
19    00cd1373    iPhone     2
20    00ecfd1a   Samsung     1
21    00fa4cd7   Samsung     2
22    01039bf1   Samsung     1
23    010b0b0b   Samsung     1
24    011beb42    iPhone     1
25    0137a57b    iPhone     1
26    0163bf88   Samsung     1
27    016a78e4    iPhone     1
28    016b86b9   Samsung     3
30    016f3833   Samsung     1
31    017fd805    iPhone     1
...        ...       ...   ...
4475  fe2df59e   Samsung     1
4476  fe3a4e34   Samsung     1
4477  fe3dccab   Samsung     1
4478  fe4029d3   Samsung     2
4479  fe469427   Samsung     1
4480  fe542b35   Samsung     1
4481  fe5679d2    iPhone     1
4482  fe87a4ba   Samsung     1
4483  fe98d076   Samsung     2
4484  febfbe81    iPhone     1
4485  fec57275   Samsung     1
4486  fed81014   Samsung    13
4487  ff277a45  Motorola     1
4488  ff28a233   Samsung     7
4490  ff2c02d6   Samsung     1
4491  ff360f9d   Samsung     1
4492  ff406fa9   Samsung     1
4493  ff415840    iPhone     2
4494  ff5bd3ac  Motorola     1
4495  ff644553   Samsung     1
4496  ff705ce5   Samsung     2
4497  ff89d18f    iPhone     2
4498  ff9e0500    iPhone     2
4499  ffc670b3   Samsung     2
4500  ffd62616   Samsung     1
4501  ffdafc72   Samsung     1
4502  ffe53446   Samsung     1
4504  ffed0342   Samsung     1
4505  fff2bdde   Samsung     1
4506  fff72025        LG     1

[4293 rows x 3 columns]

In [21]:
df_m["compro_apple"] = df_m["model_2"].apply(lambda x: 1 if x == "iPhone" else 0)
df_m["compro_samsung"] = df_m["model_2"].apply(lambda x: 1 if x == "Samsung" else 0)
df_m["compro_motorola"] = df_m["model_2"].apply(lambda x: 1 if x == "Motorola" else 0)
#df_m["vio_mas_lg"] = df_m["model_2"].apply(lambda x: 1 if x == "LG" else 0)
df_m = df_m.set_index("person")
df_m

           model_2  cant  compro_apple  compro_samsung  compro_motorola
person
000ba417  Motorola     1             0               0                1
001001be    iPhone     1             1               0                0
001804a2    iPhone     1             1               0                0
0019e639  Motorola     1             0               0                1
001b0bf9   Samsung     1             0               1                0
0020152e   Samsung     1             0               1                0
002aea56    iPhone     4             1               0                0
002ed810   Samsung     2             0               1                0
0038a117      Asus     1             0               0                0
0043a48e   Samsung     3             0               1                0
004ed8ba   Samsung     1             0               1                0
00546f4c   Samsung     4             0               1                0
00750af8   Samsung     1             0               1                0
0076b7dc    iPhone     1             1               0                0
00971729  Motorola     1             0               0                1
009944e1  Motorola     1             0               0                1
009f8292    iPhone     2             1               0                0
00caa482    iPhone     4             1               0                0
00cd1373    iPhone     2             1               0                0
00ecfd1a   Samsung     1             0               1                0
00fa4cd7   Samsung     2             0               1                0
01039bf1   Samsung     1             0               1                0
010b0b0b   Samsung     1             0               1                0
011beb42    iPhone     1             1               0                0
0137a57b    iPhone     1             1               0                0
0163bf88   Samsung     1             0               1                0
016a78e4    iPhone     1             1               0                0
016b86b9   Samsung     3             0               1                0
016f3833   Samsung     1             0               1                0
017fd805    iPhone     1             1               0                0
...            ...   ...           ...             ...              ...
fe2df59e   Samsung     1             0               1                0
fe3a4e34   Samsung     1             0               1                0
fe3dccab   Samsung     1             0               1                0
fe4029d3   Samsung     2             0               1                0
fe469427   Samsung     1             0               1                0
fe542b35   Samsung     1             0               1                0
fe5679d2    iPhone     1             1               0                0
fe87a4ba   Samsung     1             0               1                0
fe98d076   Samsung     2             0               1                0
febfbe81    iPhone     1             1               0                0
fec57275   Samsung     1             0               1                0
fed81014   Samsung    13             0               1                0
ff277a45  Motorola     1             0               0                1
ff28a233   Samsung     7             0               1                0
ff2c02d6   Samsung     1             0               1                0
ff360f9d   Samsung     1             0               1                0
ff406fa9   Samsung     1             0               1                0
ff415840    iPhone     2             1               0                0
ff5bd3ac  Motorola     1             0               0                1
ff644553   Samsung     1             0               1                0
ff705ce5   Samsung     2             0               1                0
ff89d18f    iPhone     2             1               0                0
ff9e0500    iPhone     2             1               0                0
ffc670b3   Samsung     2             0               1                0
ffd62616   Samsung     1             0               1                0
ffdafc72   Samsung     1             0               1                0
ffe53446   Samsung     1             0               1                0
ffed0342   Samsung     1             0               1                0
fff2bdde   Samsung     1             0               1                0
fff72025        LG     1             0               0                0

[4293 rows x 5 columns]

In [22]:
df_m = df_m.drop(["model_2","cant"],1)

df_m.to_csv('data/features_compras.csv', sep=',')

In [23]:
df_m

          compro_apple  compro_samsung  compro_motorola
person
000ba417             0               0                1
001001be             1               0                0
001804a2             1               0                0
0019e639             0               0                1
001b0bf9             0               1                0
0020152e             0               1                0
002aea56             1               0                0
002ed810             0               1                0
0038a117             0               0                0
0043a48e             0               1                0
004ed8ba             0               1                0
00546f4c             0               1                0
00750af8             0               1                0
0076b7dc             1               0                0
00971729             0               0                1
009944e1             0               0                1
009f8292             1               0                0
00caa482             1               0                0
00cd1373             1               0                0
00ecfd1a             0               1                0
00fa4cd7             0               1                0
01039bf1             0               1                0
010b0b0b             0               1                0
011beb42             1               0                0
0137a57b             1               0                0
0163bf88             0               1                0
016a78e4             1               0                0
016b86b9             0               1                0
016f3833             0               1                0
017fd805             1               0                0
...                ...             ...              ...
fe2df59e             0               1                0
fe3a4e34             0               1                0
fe3dccab             0               1                0
fe4029d3             0               1                0
fe469427             0               1                0
fe542b35             0               1                0
fe5679d2             1               0                0
fe87a4ba             0               1                0
fe98d076             0               1                0
febfbe81             1               0                0
fec57275             0               1                0
fed81014             0               1                0
ff277a45             0               0                1
ff28a233             0               1                0
ff2c02d6             0               1                0
ff360f9d             0               1                0
ff406fa9             0               1                0
ff415840             1               0                0
ff5bd3ac             0               0                1
ff644553             0               1                0
ff705ce5             0               1                0
ff89d18f             1               0                0
ff9e0500             1               0                0
ffc670b3             0               1                0
ffd62616             0               1                0
ffdafc72             0               1                0
ffe53446             0               1                0
ffed0342             0               1                0
fff2bdde             0               1                0
fff72025             0               0                0

[4293 rows x 3 columns]